### ISSUE TITLE
Running a python code with a daily trigger isn't re-running the python code

### ISSUE THREAD

**Issue by Nirose** [wayscript/feedback#4] opened 2019-06-05 03:52 UTC
**Describe the bug**
Running a python code with a daily trigger isn't actually running the python code. It is just using the output generated on the last "code run" (that plays the python code) for every run. 

**To Reproduce**
1. Create a python code to scrape a forex API

```python 
import requests
import json
url = 'https://www.freeforexapi.com/api/live?pairs=USDNPR'

r = requests.get(url)

data = json.loads(r.text)
if (data['code'] == 200):
  	message = str(data['rates']['USDNPR']['rate'])
    
outputs['message'] = message
```
2. Make the output be sent via email with daily trigger
3. Test the flow to see if it works. It works and gets the rate
4. But everyday it sends the same exchange rate even though the API response has different rates, so it's not really running the python code?

**Expected behavior**
It should run the code every time it is triggered, but it seems, it is using the same output from the last "code run"

**Screenshots**
![email sent](https://i.imgur.com/hFXfVDz.jpg)

**Additional context**
I just went to the flow to run the code again. it had the same output for 3 days. ran the code again to get an updated response

**Comment by jeffbuswell** [comment] 2019-06-05 18:29
Hey @Nirose, thanks for reporting this issue.  We are unable to reproduce the behavior you are seeing, but there are a couple things you can try:

1. If `data['code'] != 200`, `message` won't have a value, so you might want to assign a default value in that case
2. You can try hitting "Duplicate" on your program to create a fresh copy, and then delete the old one. See if this copy has the same issue.
![Duplicate](https://user-images.githubusercontent.com/31461850/58980379-083b1280-8785-11e9-8642-bdb254ce80a6.png)

Please let us know if either of these things work for you, or if you still see the same behavior.

**Comment by jeffbuswell** [comment] 2019-06-08 05:26
@Nirose I'm going to close this issue, but feel free to reach back out if you are still having issues.

**Closed as completed by jeffbuswell** 2019-06-08 05:26 UTC
Labels: bug
